"""Add resume_path to ResourceSecondaryInfo

Revision ID: 491cedf672b9
Revises: 
Create Date: 2024-06-19 15:42:22.266680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491cedf672b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.alter_column('hiring_manager_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('resource_hiring_manager_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'employee', ['hiring_manager_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('resource_secondary_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_secondary_info', schema=None) as batch_op:
        batch_op.drop_column('resume_path')

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('resource_hiring_manager_id_fkey', 'employee', ['hiring_manager_id'], ['id'])
        batch_op.alter_column('hiring_manager_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
